# Config file of the PvPManagerLight
#
#Permission:
#  pvpmanagerlight.*
#      pvpmanagerlight.bypass
#          pvpmanagerlight.fly
#          pvpmanagerlight.god
#          pvpmanagerlight.creative
#      pvpmanagerlight.reload
#
#
enable: true

messages:
  reload: '&aPvPManagerLight configuration reloaded.'
  nopermission: '&cYou dont have permission.'