name: PvPManagerLight
main: pml.pvpmanagerlight
author: goblin9700
version: 0.1

commands:
  pvpmanagerlight:
    description: pvpmanagerlight reload
    permission: pvpmanagerlight.reload
    usage: /pvpmanagerlight reload
    
permissions:
    pvpmanagerlight.*:
        description: Gives access to all plugin's command
        children:
            pvpmanager.reload: true
    pvpmanagerlight.reload:
        description: Allows reload plugin's config